import Head from "next/head";

import Layout from "../components/Layout";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      {/* SEO here */}
      <Head>
        <title>Énirányítok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <About />
      </Layout>
    </div>
  );
}
