import React from "react";
import Head from "next/head";

import Footer from "./Footer";
import Quote from "./Quote";

const Layout = ({ children }) => {
  return (
    <>
      {/* SEO here */}
      <Head>
        <title>Szalai Éva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>{children}</div>
      <div>
        <Quote />
        <Footer />
      </div>
    </>
  );
};

export default Layout;
